title: Introduction to Principal Component Analysis
author: Sofiene Khiari
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - ipca_references.bib
sphinx:
  config:
    bibtex_default_style: unsrt
    html_show_copyright: false
    html_theme_options:
        use_issues_button: false
        use_fullscreen_button: false
        use_repository_button: false
        use_download_button: false
        show_toc_level: 2