title: Introduction to Principal Component Analysis
author: Sofiene Khiari
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - ipca_references.bib
sphinx:
  config:
    bibtex_default_style: unsrt
    html_show_copyright: false