title: Introduction to Principal Component Analysis
author: Sofiene Khiari

repository:
  url: https://github.com/sofienekhiari/ipca

execute:
  execute_notebooks: force

bibtex_bibfiles:
  - ipca_references.bib
sphinx:
  config:
    bibtex_default_style: unsrt
    html_show_copyright: false
    html_theme_options:
        use_issues_button: true
        use_fullscreen_button: false
        use_repository_button: true
        use_edit_page_button: true
        use_download_button: false
        show_toc_level: 2